import hashlib
from providers.ransomlook.config import BASE_URL
from datetime import datetime


def format_date(raw_date):    
    dt = datetime.strptime(raw_date, "%Y-%m-%d %H:%M:%S.%f")
    return dt.strftime("%Y-%m-%d %H:%M:%S")


def compute_post_id(post):
    key = f"{post.get('post_title', '')}-{post.get('discovered', '')}"
    post['id'] = hashlib.sha256(key.encode()).hexdigest()
    return post


def format_message(post, group_info):    
    group_name = post.get('group_name', 'Unknown').title()
    description = post.get('description', None)
    victim = post.get('victim', 'No Title')
    discovered = post.get('discovered', 'N/A')
    fqdn = post.get('fqdn', 'unknown.com')
    link = post.get('link', None)
    screenshot = post.get('screenshot', None)

    ai_work_sector = post.get('ai_work_sector', None)
    ai_description = post.get('ai_description', None)
    ai_country = post.get('ai_country', None)
    
    msg = f"🚨 <b>New Ransom Post</b> 🚨\n\n" \
        f"🔎 <b>Source: <a href='{BASE_URL}'><u>RansomLook</u></a></b>\n\n" \
        f"🕷 <b>Ransom Group:\n       <a href='{BASE_URL}/group/{group_name}'><u>{group_name}</u></a></b>\n\n" \
        f"☢️​ <b>Victim:</b>\n       <code>{victim}</code>\n" \
        
    if ai_country:
        msg += f"🌍 <b>Country:</b>\n       <code>{ai_country}</code>\n"
    
    msg += f"📅 <b>Discovered:</b>\n       <code>{format_date(discovered)} CEST</code>\n"
    
    if ai_work_sector:
        msg += f"💼 <b>Work Sector:</b>\n       <code>{ai_work_sector}</code>\n"

    if description:
        msg += f"\n📝 <b>Description:</b>\n<code>{description.strip()}</code>\n"

    if ai_description:
        msg += f"\n🤖 <b>AI Enriched Description*:</b>\n<code>{ai_description.strip()}</code>\n"

    if link:
        msg += f"\n🧅 <b><a href='https://{fqdn}{link}'><u>Onion Url</u></a></b>\n"
    else:
        msg += f"\n🧅 <b><a href='https://{fqdn}'><u>Onion Url</u></a></b>\n"

    if ai_description:
        msg += "\n*AI Enriched Description is generated by AI and may not be accurate.\n"

    if screenshot:
        msg += "\n🖼  <b>Screenshot</b>  ⬇️​\n"
    
    return msg