from datetime import datetime
from providers.ransomlive.libs.mypycountries import get_country_name
from providers.ransomlive.config import BASE_URL


def format_dicovered_date(raw_date):    
    dt = datetime.strptime(raw_date, "%Y-%m-%d %H:%M:%S.%f")
    return dt.strftime("%Y-%m-%d %H:%M:%S")


def format_attack_date(raw_date):    
    dt = datetime.strptime(raw_date, "%Y-%m-%d %H:%M:%S.%f")
    return dt.strftime("%Y-%m-%d")


def format_message(post):
    group_name = post.get('group_name', 'Unknown')
    yara_link = post.get('yara_link', None)
    victim = post.get('victim', 'No Title')
    discovered = post.get('discovered', 'N/A')
    attack_date = post.get('attackdate', None)
    country = post.get('country', None)
    description = post.get('description', None)
    website = post.get('website', None)
    post_url = post.get('post_url', None)
    permalink = post.get('permalink', None)
    press = post.get('press', None)
    screenshot = post.get('screenshot', None)

    ai_work_sector = post.get('ai_work_sector', None)
    ai_description = post.get('ai_description', None)
    ai_country = post.get('ai_country', 'Unknown')
    
    msg = "🚨 <b>New Ransom Post</b> 🚨\n\n"
    msg += f"🔎 <b>Source: <a href='{BASE_URL}'><u>Ransomware.live</u></a></b>\n\n"
    msg += f"🕷 <b>Ransom Group:\n       <a href='{BASE_URL}/group/{group_name}'><u>{group_name.title()}</u></a></b>\n"    
    msg += f"\n🧩 <b><a href='{BASE_URL}/ioc'><u>IOCs</u></a></b>\n"
    if yara_link:
        msg += f"🧬 <b><a href='{yara_link}'><u>YARA Rule for {group_name.title()}</u></a></b>\n"        
    msg += f"\n☢️​ <b>Victim:</b>\n       <code>{victim}</code>\n"
    msg += f"🌍 <b>Country:</b>\n       <code>{get_country_name(country) if country else ai_country}</code>\n"
    msg += f"📅 <b>Discovered:</b>\n       <code>{format_dicovered_date(discovered)} CEST</code>\n"

    if attack_date:
        msg += f"⚠️ <b>Attack Date:</b>\n       <code>{format_attack_date(attack_date)} CEST</code>\n"

    if website:
        msg += f"🌐 <b>Website:\n       <a href='{website}'><u>{website}</u></a></b>\n"

    if ai_work_sector:
        msg += f"💼 <b>Work Sector*:</b>\n       <code>{ai_work_sector}</code>\n"

    if description:
        msg += f"\n📝 <b>Description:</b>\n<code>{description.strip()}</code>\n"

    if ai_description:
        msg += f"\n🤖 <b>AI Enriched Description*:</b>\n<code>{ai_description.strip()}</code>\n"

    if press:
        msg += f"\n🗞️ <b>Press:</b>  <a href='{press}'><u>Press article</u></a>\n"
    
    if post_url:  
        msg += f"\n🧅  <b><a href='{post_url}'><u>Onion Url</u></a></b>\n"

    msg += f"\n🔗  <b><a href='{permalink}'><u>Post Details</u></a></b>\n"

    if ai_description:
        msg += "\n*The data is generated by AI and may not be accurate.\n"
        
    if screenshot:
        msg += "\n🖼  <b>Screenshot</b>  ⬇️​\n"

    return msg